
Organizations:
    - &${TC_ORDERER1_STACK}
        Name: ${TC_ORDERER1_STACK}
        ID: ${TC_ORDERER1_STACK}MSP
        MSPDir: ${TC_ORDERER1_DATA}/msp
        Policies: &${TC_ORDERER1_STACK}Policies
            Readers:
                Type: Signature
                Rule: "OR('${TC_ORDERER1_STACK}MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('${TC_ORDERER1_STACK}MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('${TC_ORDERER1_STACK}MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('${TC_ORDERER1_STACK}MSP.member')"
        OrdererEndpoints:
            - ${TC_ORDERER1_O1_FQDN}:${TC_ORDERER1_O1_PORT}
            - ${TC_ORDERER1_O2_FQDN}:${TC_ORDERER1_O2_PORT}
            - ${TC_ORDERER1_O3_FQDN}:${TC_ORDERER1_O3_PORT}
    - &${TC_ORG1_STACK}
        Name: ${TC_ORG1_STACK}MSP
        ID: ${TC_ORG1_STACK}MSP
        MSPDir: ${TC_ORG1_DATA}/msp
        Policies: &${TC_ORG1_STACK}Policies
            Readers:
                Type: Signature
                Rule: "OR('${TC_ORG1_STACK}MSP.admin', '${TC_ORG1_STACK}MSP.peer', '${TC_ORG1_STACK}MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('${TC_ORG1_STACK}MSP.admin', '${TC_ORG1_STACK}MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('${TC_ORG1_STACK}MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('${TC_ORG1_STACK}MSP.peer')"
        AnchorPeers:
            - Host: $TC_ORG1_P1_FQDN
              Port: $TC_ORG1_P1_PORT
    - &${TC_ORG2_STACK}
        Name: ${TC_ORG2_STACK}MSP
        ID: ${TC_ORG2_STACK}MSP
        MSPDir: ${TC_ORG2_DATA}/msp
        Policies: &${TC_ORG2_STACK}Policies
            Readers:
                Type: Signature
                Rule: "OR('${TC_ORG2_STACK}MSP.admin', '${TC_ORG2_STACK}MSP.peer', '${TC_ORG2_STACK}MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('${TC_ORG2_STACK}MSP.admin', '${TC_ORG2_STACK}MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('${TC_ORG2_STACK}MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('${TC_ORG2_STACK}MSP.peer')"
        AnchorPeers:
            - Host: $TC_ORG2_P1_FQDN
              Port: $TC_ORG2_P1_PORT
    - &${TC_ORG3_STACK}
        Name: ${TC_ORG3_STACK}MSP
        ID: ${TC_ORG3_STACK}MSP
        MSPDir: ${TC_ORG3_DATA}/msp
        Policies: &${TC_ORG3_STACK}Policies
            Readers:
                Type: Signature
                Rule: "OR('${TC_ORG3_STACK}MSP.admin', '${TC_ORG3_STACK}MSP.peer', '${TC_ORG3_STACK}MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('${TC_ORG3_STACK}MSP.admin', '${TC_ORG3_STACK}MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('${TC_ORG3_STACK}MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('${TC_ORG3_STACK}MSP.peer')"
        AnchorPeers:
            - Host: $TC_ORG3_P1_FQDN
              Port: $TC_ORG3_P1_PORT
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_5: true
Application: &ApplicationDefaults
    Organizations:
        # - ${TC_ORG1_STACK}
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities
Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - ${TC_ORDERER1_O1_FQDN}:${TC_ORDERER1_O1_PORT}
        - ${TC_ORDERER1_O2_FQDN}:${TC_ORDERER1_O2_PORT}
        - ${TC_ORDERER1_O3_FQDN}:${TC_ORDERER1_O3_PORT}
    EtcdRaft:
        Consenters:
        - Host: ${TC_ORDERER1_O1_FQDN}
          Port: ${TC_ORDERER1_O1_PORT}
          ClientTLSCert: ${TC_ORDERER1_O1_TLSMSP}/signcerts/cert.pem
          ServerTLSCert: ${TC_ORDERER1_O1_TLSMSP}/signcerts/cert.pem
        - Host: ${TC_ORDERER1_O2_FQDN}
          Port: ${TC_ORDERER1_O2_PORT}
          ClientTLSCert: ${TC_ORDERER1_O2_TLSMSP}/signcerts/cert.pem
          ServerTLSCert: ${TC_ORDERER1_O2_TLSMSP}/signcerts/cert.pem
        - Host: ${TC_ORDERER1_O3_FQDN}
          Port: ${TC_ORDERER1_O3_PORT}
          ClientTLSCert: ${TC_ORDERER1_O3_TLSMSP}/signcerts/cert.pem
          ServerTLSCert: ${TC_ORDERER1_O3_TLSMSP}/signcerts/cert.pem
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 49 MB
        PreferredMaxBytes: 512 KB
    Organizations:
        # - ${TC_ORDERER1_STACK}
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities
Profiles:
    ${TC_CHANNEL_PROFILE}:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            Organizations:
                - <<: *${TC_ORDERER1_STACK}
                  Policies:
                      <<: *${TC_ORDERER1_STACK}Policies
                      Admins:
                          Type: Signature
                          Rule: "OR('${TC_ORDERER1_STACK}.member')"
            # Capabilities: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - <<: *${TC_ORG1_STACK}
                  Policies:
                      <<: *${TC_ORG1_STACK}Policies
                      Admins:
                          Type: Signature
                          Rule: "OR('${TC_ORG1_STACK}.admin')"
                - <<: *${TC_ORG2_STACK}
                  Policies:
                      <<: *${TC_ORG2_STACK}Policies
                      Admins:
                          Type: Signature
                          Rule: "OR('${TC_ORG2_STACK}.admin')"
                - <<: *${TC_ORG3_STACK}
                  Policies:
                      <<: *${TC_ORG3_STACK}Policies
                      Admins:
                          Type: Signature
                          Rule: "OR('${TC_ORG3_STACK}.admin')"
            # Capabilities: *ApplicationCapabilities
