global:
  scrape_interval: 5s
  external_labels:
    monitor: "devopsage-monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "${TC_ORDERER1_O1_FQDN}"
    static_configs:
      - targets: ["${TC_ORDERER1_O1_FQDN}:${TC_ORDERER1_O1_OPPORT}"]
  - job_name: "${TC_ORDERER1_O2_FQDN}"
    static_configs:
      - targets: ["${TC_ORDERER1_O2_FQDN}:${TC_ORDERER1_O2_OPPORT}"]
  - job_name: "${TC_ORDERER1_O3_FQDN}"
    static_configs:
      - targets: ["${TC_ORDERER1_O3_FQDN}:${TC_ORDERER1_O3_OPPORT}"]
  - job_name: "${TC_ORG1_O1_FQDN}"
    static_configs:
      - targets: ["${TC_ORG1_O1_FQDN}:${TC_ORG1_O1_OPPORT}"]
  - job_name: "${TC_ORG1_O2_FQDN}"
    static_configs:
      - targets: ["${TC_ORG1_O2_FQDN}:${TC_ORG1_O2_OPPORT}"]
  - job_name: "${TC_ORG1_O3_FQDN}"
    static_configs:
      - targets: ["${TC_ORG1_O3_FQDN}:${TC_ORG1_O3_OPPORT}"]
 - job_name: "${TC_ORG2_O1_FQDN}"
    static_configs:
      - targets: ["${TC_ORG2_O1_FQDN}:${TC_ORG2_O1_OPPORT}"]
  - job_name: "${TC_ORG2_O2_FQDN}"
    static_configs:
      - targets: ["${TC_ORG2_O2_FQDN}:${TC_ORG2_O2_OPPORT}"]
  - job_name: "${TC_ORG2_O3_FQDN}"
    static_configs:
      - targets: ["${TC_ORG2_O3_FQDN}:${TC_ORG2_O3_OPPORT}"]
  - job_name: "${TC_COMMON1_S4_NAME}"
    scrape_interval: 5s
    static_configs:
      - targets: ["${TC_COMMON1_S4_NAME}:8080"]
  - job_name: "${TC_COMMON1_S5_NAME}"
    static_configs:
      - targets: ["${TC_COMMON1_S5_NAME}":9100"]
