url: https://0.0.0.0:${TC_COMMON1_C1_PORT}
# mspdir: msp
debug: false

tls:
  enabled: true

csr:
  cn: ${TC_COMMON1_STACK}-${TC_COMMON1_C1_NAME}
  names:
    - C:
      ST:
      L:
      O: "${TC_NETWORK_NAME}"
      OU: "${TC_COMMON1_STACK}"
  # cn: ${TC_COMMON1_C1_NAME}-${TC_COMMON1_STACK}
  # names:
  #   - C: "${TC_COMMON1_C}"
  #     ST: "${TC_COMMON1_ST}"
  #     L: "${TC_COMMON1_L}"
  #     O: "${TC_COMMON1_O}"
  #     OU: "${TC_COMMON1_OU}"

id:
  name:
  type:
  # affiliation: ${TC_COMMON1_STACK}
  maxenrollments: 0
  attributes:
