port: ${TC_ORDERER1_C1_PORT}
debug: ${TC_ORDERER1_C1_DEBUG}

tls:
  enabled: true

registry:
  maxenrollments: -1
  identities:
     - name: ${TC_ORDERER1_C1_ADMIN}
       pass: ${TC_ORDERER1_C1_ADMINPW}
       type: client
      #  affiliation: ${TC_COMMON1_STACK}
       attrs:
          hf.Registrar.Roles: "*"
          hf.Registrar.DelegateRoles: "*"
          hf.Revoker: true
          hf.IntermediateCA: true
          hf.GenCRL: true
          hf.Registrar.Attributes: "*"
          hf.AffiliationMgr: true

signing:
    default:
      expiry: ${TC_ORDERER1_C1_EXP}
    profiles:
      ca:
         expiry: ${TC_ORDERER1_C1_EXP}
      tls:
         expiry: ${TC_ORDERER1_C1_EXP}

csr:
  # cn: ${TC_ORDERER1_STACK}-${TC_ORDERER1_C1_NAME}
  cn: ${TC_ORDERER1_C1_FQDN}  
  names:
    - C:
      ST:
      L:
      OU:
      O: "${TC_ORDERER1_STACK}"
  hosts:
    - ${TC_ORDERER1_C1_FQDN}
    - localhost
    - 0.0.0.0
  ca:
    expiry: ${TC_ORDERER1_C1_EXP}
