version: "3.7"

networks:
  ${TC_NETWORK_NAME}:
    name: ${TC_NETWORK_NAME}
    external: true

services:
  ${TC_COMMON1_C1_NAME}:
    command: sh -c 'fabric-ca-server start -b ${TC_COMMON1_C1_ADMIN}:${TC_COMMON1_C1_ADMINPW} --port ${TC_COMMON1_C1_PORT}'
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == ${TC_COMMON1_C1_WORKER} ]
    environment:
      - FABRIC_CA_SERVER_HOME=${TC_COMMON1_C1_HOME}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=${TC_COMMON1_C1_NAME}-${TC_COMMON1_STACK}
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=${TC_COMMON1_C1_DEBUG}
      - FABRIC_CA_SERVER_SIGNING_DEFAULT_EXPIRY=876000h
      - FABRIC_CA_SERVER_SIGNING_PROFILES_CA_EXPIRY=876000h
      - FABRIC_CA_SERVER_SIGNING_PROFILES_TLS_EXPIRY=876000h
      - FABRIC_CA_SERVER_CSR_CA_EXPIRY=876000h
    hostname: ${TC_COMMON1_C1_FQDN} 
    image: hyperledger/fabric-ca:${TC_DEPS_CA}
    labels:
      service: ${TC_COMMON1_C1_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_COMMON1_C1_NAME}
          - ${TC_COMMON1_C1_FQDN}
    ports:
      - ${TC_COMMON1_C1_PORT}:${TC_COMMON1_C1_PORT}
    volumes:
      - ${TC_COMMON1_C1_DATA}:${TC_COMMON1_C1_DATA}
  # ${TC_COMMON1_F1_NAME}:
  #   cap_add:
  #     - ALL
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints: [ node.hostname == ${TC_COMMON1_F1_WORKER} ]
  #   environment:
  #     - SHARED_DIRECTORY=${TC_COMMON1_F1_DATA}
  #   hostname: ${TC_COMMON1_F1_FQDN}
  #   image: ${TC_COMMON1_F1_IMAGE}
  #   labels:
  #     service: ${TC_COMMON1_F1_FQDN}
  #   networks:
  #     ${TC_SWARM_NETNAME}:
  #       aliases:
  #         - ${TC_COMMON1_F1_NAME}
  #         - ${TC_COMMON1_F1_FQDN}
  #   ports:
  #     - ${TC_COMMON1_F1_PORT}:2049
  #   privileged: true
  #   # restart: unless-stopped
  #   volumes:
  #     - ${TC_COMMON1_F1_DATA}:${TC_COMMON1_F1_DATA}
