version: "3.7"

networks:
  ${TC_SWARM_NETNAME}:
    name: ${TC_SWARM_NETNAME}
    external: true

services:
  ${TC_TLSCA1_C1_NAME}:
    command: sh -c 'fabric-ca-server start -b ${TC_TLSCA1_C1_ADMIN}:${TC_TLSCA1_C1_ADMINPW} --port ${TC_TLSCA1_C1_PORT}'
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == ${TC_TLSCA1_C1_WORKER} ]
    environment:
      - FABRIC_CA_SERVER_HOME=${TC_TLSCA1_C1_HOME}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=${TC_TLSCA1_STACK}_${TC_TLSCA1_C1_NAME}
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=${TC_TLSCA1_C1_DEBUG}
    hostname: ${TC_TLSCA1_C1_FQDN} 
    image: hyperledger/fabric-ca:${TC_DEPS_CA}
    labels:
      service: ${TC_TLSCA1_C1_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_TLSCA1_C1_NAME}
          - ${TC_TLSCA1_C1_FQDN}
    ports:
      - ${TC_TLSCA1_C1_PORT}:${TC_TLSCA1_C1_PORT}
    volumes:
      - ${TC_TLSCA1_C1_DATA}:${TC_TLSCA1_C1_DATA}
