version: "3.7"

networks:
  ${TC_NETWORK_NAME}:
    name: ${TC_NETWORK_NAME}
    external: true

secrets:
  tc_https_cert:
    external: true
  tc_https_key:
    external: true

services:
  ${TC_COMMON1_REGISTRY_NAME}:
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == ${TC_COMMON1_REGISTRY_WORKER} ]
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=${TC_COMMON1_REGISTRY_DATA}
      - REGISTRY_HTTP_ADDR=0.0.0.0:${TC_COMMON1_REGISTRY_PORT}
    hostname: ${TC_COMMON1_REGISTRY_FQDN} 
    image: registry:2
    labels:
      service: ${TC_COMMON1_REGISTRY_FQDN}
      # registry: true
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_COMMON1_REGISTRY_NAME}
          - ${TC_COMMON1_REGISTRY_FQDN}
    ports:
      - ${TC_COMMON1_REGISTRY_PORT}:${TC_COMMON1_REGISTRY_PORT}
    # restart: always
    secrets:
      - tc_https_cert
      - tc_https_key
    volumes:
      - ${TC_COMMON1_REGISTRY_DATA}:${TC_COMMON1_REGISTRY_DATA}

  ${TC_COMMON1_C1_NAME}:
    command: sh -c 'fabric-ca-server start -b ${TC_COMMON1_C1_ADMIN}:${TC_COMMON1_C1_ADMINPW} --port ${TC_COMMON1_C1_PORT}'
    depends_on:
      - ${TC_COMMON1_REGISTRY_FQDN}
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == ${TC_COMMON1_C1_WORKER} ]
    environment:
      - FABRIC_CA_SERVER_HOME=${TC_COMMON1_C1_HOME}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=${TC_COMMON1_C1_NAME}-${TC_COMMON1_STACK}
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=${TC_COMMON1_C1_DEBUG}
      - FABRIC_CA_SERVER_SIGNING_DEFAULT_EXPIRY=876000h
      - FABRIC_CA_SERVER_SIGNING_PROFILES_CA_EXPIRY=876000h
      - FABRIC_CA_SERVER_SIGNING_PROFILES_TLS_EXPIRY=876000h
      - FABRIC_CA_SERVER_CSR_CA_EXPIRY=876000h
    hostname: ${TC_COMMON1_C1_FQDN} 
    image: ${TC_SWARM_IMG_CA}
    labels:
      service: ${TC_COMMON1_C1_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_COMMON1_C1_NAME}
          - ${TC_COMMON1_C1_FQDN}
    ports:
      - ${TC_COMMON1_C1_PORT}:${TC_COMMON1_C1_PORT}
    volumes:
      - ${TC_COMMON1_C1_DATA}:${TC_COMMON1_C1_DATA}
