version: "3.7"

networks:
  ${TC_SWARM_NETNAME}:
    name: ${TC_SWARM_NETNAME}
    external: true

services:
  ${TC_ORDERER1_C1_NAME}:
    command: /bin/bash -c 'fabric-ca-server start -b ${TC_ORDERER1_C1_ADMIN}:${TC_ORDERER1_C1_ADMINPW} --port ${TC_ORDERER1_C1_PORT}'
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == ${TC_ORDERER1_C1_WORKER} ]
    environment:
      - FABRIC_CA_SERVER_HOME=${TC_ORDERER1_C1_HOME}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=${TC_ORDERER1_C1_NAME}-${TC_ORDERER1_STACK}
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=${TC_ORDERER1_C1_DEBUG}
    hostname: ${TC_ORDERER1_C1_FQDN} 
    image: hyperledger/fabric-ca:${TC_DEPS_CA}
    labels:
      service: ${TC_ORDERER1_C1_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_ORDERER1_C1_NAME}
          - ${TC_ORDERER1_C1_FQDN}
    ports:
      - ${TC_ORDERER1_C1_PORT}:${TC_ORDERER1_C1_PORT}
    volumes:
      - ${TC_ORDERER1_C1_DATA}:${TC_ORDERER1_C1_DATA}

  ${TC_ORDERER1_O1_NAME}:
    deploy:
      replicas: 0
      placement:
        constraints: [ node.hostname == ${TC_ORDERER1_O1_WORKER} ]
    environment:
      - FABRIC_LOGGING_SPEC=${TC_ORDERER1_O1_LOGLEVEL}
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:${TC_ORDERER1_O1_ADMINPORT}
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_PRIVATEKEY=${TC_ORDERER1_O1_TLSMSP}/keystore/key.pem
      - ORDERER_ADMIN_TLS_CERTIFICATE=${TC_ORDERER1_O1_TLSMSP}/signcerts/cert.pem
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[${TC_ORDERER1_O1_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_TLSCA_C1_PORT}.pem]
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_CONSENSUS_WALDIR=${TC_ORG1_P1_DATA}
      - ORDERER_CONSENSUS_SNAPDIR=${TC_ORG1_P1_DATA}
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=${TC_ORDERER1_O1_PORT}
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=${TC_ORDERER1_O1_TLSMSP}/keystore/key.pem
      - ORDERER_GENERAL_TLS_CERTIFICATE=${TC_ORDERER1_O1_TLSMSP}/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[${TC_ORDERER1_O1_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_TLSCA_C1_PORT}.pem]
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
      # - ORDERER_GENERAL_TLS_CLIENTROOTCAS=[${TC_ORDERER1_O1_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_TLSCA_C1_PORT}.pem]
      - ORDERER_GENERAL_LOCALMSPDIR=${TC_ORDERER1_O1_MSP}
      - ORDERER_GENERAL_LOCALMSPID=${TC_ORDERER1_STACK}MSP
      - ORDERER_HOME=${TC_ORG1_P1_DATA}
      - ORDERER_HOST=${TC_ORDERER1_O1_NAME}
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:${TC_ORDERER1_O1_OPPORT}
      - ORDERER_OPERATIONS_TLS_ENABLED=true
      - ORDERER_OPERATIONS_TLS_CERTIFICATE=${TC_ORDERER1_O1_TLSMSP}/signcerts/cert.pem
      - ORDERER_OPERATIONS_TLS_PRIVATEKEY=${TC_ORDERER1_O1_TLSMSP}/keystore/key.pem
      - ORDERER_OPERATIONS_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_OPERATIONS_TLS_CLIENTROOTCAS=[${TC_ORDERER1_O1_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_TLSCA_C1_PORT}.pem]
    hostname: ${TC_ORDERER1_O1_FQDN}
    image: hyperledger/fabric-orderer:${TC_DEPS_FABRIC}
    labels:
      service: ${TC_ORDERER1_O1_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_ORDERER1_O1_NAME}
          - ${TC_ORDERER1_O1_FQDN}
    ports:
      - ${TC_ORDERER1_O1_PORT}:${TC_ORDERER1_O1_PORT}
      - ${TC_ORDERER1_O1_ADMINPORT}:${TC_ORDERER1_O1_ADMINPORT}
      - ${TC_ORDERER1_O1_OPPORT}:${TC_ORDERER1_O1_OPPORT}
    volumes:
      - ${TC_ORDERER1_O1_DATA}:${TC_ORDERER1_O1_DATA}
  ${TC_ORDERER1_O2_NAME}:
    deploy:
      replicas: 0
      placement:
        constraints: [ node.hostname == ${TC_ORDERER1_O2_WORKER} ]
    environment:
      - FABRIC_LOGGING_SPEC=${TC_ORDERER1_O2_LOGLEVEL}
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:${TC_ORDERER1_O2_ADMINPORT}
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_PRIVATEKEY=${TC_ORDERER1_O2_TLSMSP}/keystore/key.pem
      - ORDERER_ADMIN_TLS_CERTIFICATE=${TC_ORDERER1_O2_TLSMSP}/signcerts/cert.pem
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[${TC_ORDERER1_O2_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_TLSCA_C1_PORT}.pem]
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_CONSENSUS_WALDIR=${TC_ORG1_P1_DATA}
      - ORDERER_CONSENSUS_SNAPDIR=${TC_ORG1_P1_DATA}
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=${TC_ORDERER1_O2_PORT}
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=${TC_ORDERER1_O2_TLSMSP}/keystore/key.pem
      - ORDERER_GENERAL_TLS_CERTIFICATE=${TC_ORDERER1_O2_TLSMSP}/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[${TC_ORDERER1_O2_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_TLSCA_C1_PORT}.pem]
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
      # - ORDERER_GENERAL_TLS_CLIENTROOTCAS=[${TC_ORDERER1_O2_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_TLSCA_C1_PORT}.pem]
      - ORDERER_GENERAL_LOCALMSPDIR=${TC_ORDERER1_O2_MSP}
      - ORDERER_GENERAL_LOCALMSPID=${TC_ORDERER1_STACK}MSP
      - ORDERER_HOME=${TC_ORG1_P1_DATA}
      - ORDERER_HOST=${TC_ORDERER1_O2_NAME}
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:${TC_ORDERER1_O2_OPPORT}
      - ORDERER_OPERATIONS_TLS_ENABLED=true
      - ORDERER_OPERATIONS_TLS_CERTIFICATE=${TC_ORDERER1_O2_TLSMSP}/signcerts/cert.pem
      - ORDERER_OPERATIONS_TLS_PRIVATEKEY=${TC_ORDERER1_O2_TLSMSP}/keystore/key.pem
      - ORDERER_OPERATIONS_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_OPERATIONS_TLS_CLIENTROOTCAS=[${TC_ORDERER1_O2_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_TLSCA_C1_PORT}.pem]
    hostname: ${TC_ORDERER1_O2_FQDN}
    image: hyperledger/fabric-orderer:${TC_DEPS_FABRIC}
    labels:
      service: ${TC_ORDERER1_O2_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_ORDERER1_O2_NAME}
          - ${TC_ORDERER1_O2_FQDN}
    ports:
      - ${TC_ORDERER1_O2_PORT}:${TC_ORDERER1_O2_PORT}
      - ${TC_ORDERER1_O2_ADMINPORT}:${TC_ORDERER1_O2_ADMINPORT}
      - ${TC_ORDERER1_O2_OPPORT}:${TC_ORDERER1_O2_OPPORT}
    volumes:
      - ${TC_ORDERER1_O2_DATA}:${TC_ORDERER1_O2_DATA}
  ${TC_ORDERER1_O3_NAME}:
    deploy:
      replicas: 0
      placement:
        constraints: [ node.hostname == ${TC_ORDERER1_O3_WORKER} ]
    environment:
      - FABRIC_LOGGING_SPEC=${TC_ORDERER1_O3_LOGLEVEL}
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:${TC_ORDERER1_O3_ADMINPORT}
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_PRIVATEKEY=${TC_ORDERER1_O3_TLSMSP}/keystore/key.pem
      - ORDERER_ADMIN_TLS_CERTIFICATE=${TC_ORDERER1_O3_TLSMSP}/signcerts/cert.pem
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[${TC_ORDERER1_O3_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_TLSCA_C1_PORT}.pem]
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_CONSENSUS_WALDIR=${TC_ORG1_P1_DATA}
      - ORDERER_CONSENSUS_SNAPDIR=${TC_ORG1_P1_DATA}
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=${TC_ORDERER1_O3_PORT}
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=${TC_ORDERER1_O3_TLSMSP}/keystore/key.pem
      - ORDERER_GENERAL_TLS_CERTIFICATE=${TC_ORDERER1_O3_TLSMSP}/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[${TC_ORDERER1_O3_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_TLSCA_C1_PORT}.pem]
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
      # - ORDERER_GENERAL_TLS_CLIENTROOTCAS=[${TC_ORDERER1_O3_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_TLSCA_C1_PORT}.pem]
      - ORDERER_GENERAL_LOCALMSPDIR=${TC_ORDERER1_O3_MSP}
      - ORDERER_GENERAL_LOCALMSPID=${TC_ORDERER1_STACK}MSP
      - ORDERER_HOME=${TC_ORG1_P1_DATA}
      - ORDERER_HOST=${TC_ORDERER1_O3_NAME}
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:${TC_ORDERER1_O3_OPPORT}
      - ORDERER_OPERATIONS_TLS_ENABLED=true
      - ORDERER_OPERATIONS_TLS_CERTIFICATE=${TC_ORDERER1_O3_TLSMSP}/signcerts/cert.pem
      - ORDERER_OPERATIONS_TLS_PRIVATEKEY=${TC_ORDERER1_O3_TLSMSP}/keystore/key.pem
      - ORDERER_OPERATIONS_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_OPERATIONS_TLS_CLIENTROOTCAS=[${TC_ORDERER1_O3_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_TLSCA_C1_PORT}.pem]
    hostname: ${TC_ORDERER1_O3_FQDN}
    image: hyperledger/fabric-orderer:${TC_DEPS_FABRIC}
    labels:
      service: ${TC_ORDERER1_O3_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_ORDERER1_O3_NAME}
          - ${TC_ORDERER1_O3_FQDN}
    ports:
      - ${TC_ORDERER1_O3_PORT}:${TC_ORDERER1_O3_PORT}
      - ${TC_ORDERER1_O3_ADMINPORT}:${TC_ORDERER1_O3_ADMINPORT}
      - ${TC_ORDERER1_O3_OPPORT}:${TC_ORDERER1_O3_OPPORT}
    volumes:
      - ${TC_ORDERER1_O3_DATA}:${TC_ORDERER1_O3_DATA}
