version: "3.7"

networks:
  ${TC_SWARM_NETNAME}:
    name: ${TC_SWARM_NETNAME}
    external: true

services:
  ${TC_ORG3_C1_NAME}:
    command: /bin/bash -c 'fabric-ca-server start -b ${TC_ORG3_C1_ADMIN}:${TC_ORG3_C1_ADMINPW} --port ${TC_ORG3_C1_PORT}'
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == ${TC_ORG3_C1_WORKER} ]
    environment:
      - FABRIC_CA_SERVER_HOME=${TC_ORG3_C1_HOME}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=${TC_ORG3_C1_NAME}-${TC_ORG3_STACK}
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=${TC_ORG3_C1_DEBUG}
      - FABRIC_CA_SERVER_LOGLEVEL=${TC_ORG3_C1_LOGLEVEL}
      - FABRIC_CA_SERVER_SIGNING_DEFAULT_EXPIRY=876000h
      - FABRIC_CA_SERVER_SIGNING_PROFILES_CA_EXPIRY=876000h
      - FABRIC_CA_SERVER_SIGNING_PROFILES_TLS_EXPIRY=876000h
      - FABRIC_CA_SERVER_CSR_CA_EXPIRY=876000h
    hostname: ${TC_ORG3_C1_FQDN} 
    image: hyperledger/fabric-ca:${TC_DEPS_CA}
    labels:
      service: ${TC_ORG3_C1_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_ORG3_C1_NAME}
          - ${TC_ORG3_C1_FQDN}
    ports:
      - ${TC_ORG3_C1_PORT}:${TC_ORG3_C1_PORT}
    volumes:
      - ${TC_ORG3_C1_DATA}:${TC_ORG3_C1_DATA}

  ${TC_ORG3_D1_NAME}:
    deploy: 
      replicas: 1
      placement:
        constraints: [node.hostname == ${TC_ORG3_D1_WORKER}]
      restart_policy:
        condition: any 
        delay: ${TC_SWARM_DELAY}s
        max_attempts: 5
    environment:
      - COUCHDB_USER=${TC_ORG3_D1_USER}
      - COUCHDB_PASSWORD=${TC_ORG3_D1_USERPW}
    hostname: ${TC_ORG3_D1_FQDN}
    image: couchdb:${TC_DEPS_COUCHDB}
    labels:
      service: ${TC_ORG3_D1_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_ORG3_D1_NAME}
          - ${TC_ORG3_D1_FQDN}
    ports:
      - "${TC_ORG3_D1_PORT}:5984"
    volumes:
      - ${TC_ORG3_D1_DATA}:/opt/couchdb/data
  ${TC_ORG3_D2_NAME}:
    deploy: 
      replicas: 1
      placement:
        constraints: [node.hostname == ${TC_ORG3_D2_WORKER}]
      restart_policy:
        condition: any 
        delay: ${TC_SWARM_DELAY}s
        max_attempts: 5
    environment:
      - COUCHDB_USER=${TC_ORG3_D2_USER}
      - COUCHDB_PASSWORD=${TC_ORG3_D2_USERPW}
    hostname: ${TC_ORG3_D2_FQDN}
    image: couchdb:${TC_DEPS_COUCHDB}
    labels:
      service: ${TC_ORG3_D2_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_ORG3_D2_NAME}
          - ${TC_ORG3_D2_FQDN}
    ports:
      - "${TC_ORG3_D2_PORT}:5984"
    volumes:
      - ${TC_ORG3_D2_DATA}:/opt/couchdb/data
  ${TC_ORG3_D3_NAME}:
    deploy: 
      replicas: 1
      placement:
        constraints: [node.hostname == ${TC_ORG3_D3_WORKER}]
      restart_policy:
        condition: any 
        delay: ${TC_SWARM_DELAY}s
        max_attempts: 5
    environment:
      - COUCHDB_USER=${TC_ORG3_D3_USER}
      - COUCHDB_PASSWORD=${TC_ORG3_D3_USERPW}
    hostname: ${TC_ORG3_D3_FQDN}
    image: couchdb:${TC_DEPS_COUCHDB}
    labels:
      service: ${TC_ORG3_D3_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_ORG3_D3_NAME}
          - ${TC_ORG3_D3_FQDN}
    ports:
      - "${TC_ORG3_D3_PORT}:5984"
    volumes:
      - ${TC_ORG3_D3_DATA}:/opt/couchdb/data

  ${TC_ORG3_P1_NAME}:
    depends_on:
      - ${TC_ORG3_D1_FQDN}
    deploy:
      placement:
        constraints: [ node.hostname == ${TC_ORG3_P1_WORKER} ]
      replicas: 0
      restart_policy:
        condition: any 
        delay: ${TC_SWARM_DELAY}s
        max_attempts: 5
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=${TC_ORG3_D1_FQDN}:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${TC_ORG3_D1_USER}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${TC_ORG3_D1_USERPW}
      - CORE_LEDGER_SNAPSHOTS_ROOTDIR=${TC_ORG3_P1_DATA}/snapshots
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:${TC_ORG3_P1_OPPORT}
      # - CORE_OPERATIONS_TLS_CERT_FILE=${TC_ORG3_P1_TLSMSP}/signcerts/cert.pem
      # - CORE_OPERATIONS_TLS_KEY_FILE=${TC_ORG3_P1_TLSMSP}/keystore/key.pem
      # - CORE_OPERATIONS_TLS_CLIENTAUTHREQUIRED=true
      # - CORE_OPERATIONS_TLS_CLIENTROOTCAS_FILES:
      #   - ${TC_ORG3_P1_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_COMMON1_C1_PORT}.pem
      - CORE_PEER_ADDRESS=${TC_ORG3_P1_FQDN}:${TC_ORG3_P1_PORT}
      - CORE_PEER_CHAINCODEADDRESS=${TC_ORG3_P1_FQDN}:${TC_ORG3_P1_CHPORT}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${TC_ORG3_P1_CHPORT}
      - CORE_PEER_ID=${TC_ORG3_P1_CA_NAME}
      - CORE_PEER_FILESYSTEMPATH=${TC_ORG3_P1_DATA}
      - CORE_PEER_GOSSIP_BOOTSTRAP=127.0.0.1:${TC_ORG3_P1_PORT}
      - CORE_PEER_GOSSIP_ENDPOINT=${TC_ORG3_P1_FQDN}:${TC_ORG3_P1_PORT}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${TC_ORG3_P1_FQDN}:${TC_ORG3_P1_PORT}
      - CORE_PEER_GOSSIP_ORGLEADER=true
      # - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_GOSSIP_STATE_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${TC_ORG3_P1_PORT}
      - CORE_PEER_LOCALMSPID=${TC_ORG3_STACK}MSP
      - CORE_PEER_NETWORKID=${TC_SWARM_NETNAME}
      - CORE_PEER_MSPCONFIGPATH=${TC_ORG3_P1_MSP}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=${TC_ORG3_P1_TLSMSP}/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=${TC_ORG3_P1_TLSMSP}/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=${TC_ORG3_P1_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_COMMON1_C1_PORT}.pem
      # - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES:
      #     - ${TC_ORG3_P1_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_COMMON1_C1_PORT}.pem
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${TC_NETWORK_NAME}
      - FABRIC_LOGGING_SPEC=${TC_ORG3_P1_LOGLEVEL}
    hostname: ${TC_ORG3_P1_FQDN}
    image: hyperledger/fabric-peer:${TC_DEPS_FABRIC}
    labels:
      service: ${TC_ORG3_P1_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_ORG3_P1_NAME}
          - ${TC_ORG3_P1_FQDN}
    ports:
      - ${TC_ORG3_P1_PORT}:${TC_ORG3_P1_PORT}
      - ${TC_ORG3_P1_CHPORT}:${TC_ORG3_P1_CHPORT}
      - ${TC_ORG3_P1_OPPORT}:${TC_ORG3_P1_OPPORT}
    volumes:
      - ${TC_ORG3_P1_DATA}:${TC_ORG3_P1_DATA} 
      - /var/run/:/host/var/run/
    working_dir: ${TC_ORG3_P1_DATA}
  ${TC_ORG3_P2_NAME}:
    depends_on:
      - ${TC_ORG3_D2_FQDN}
    deploy:
      placement:
        constraints: [ node.hostname == ${TC_ORG3_P2_WORKER} ]
      replicas: 0
      restart_policy:
        condition: any 
        delay: ${TC_SWARM_DELAY}s
        max_attempts: 5
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=${TC_ORG3_D2_FQDN}:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${TC_ORG3_D2_USER}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${TC_ORG3_D2_USERPW}
      - CORE_LEDGER_SNAPSHOTS_ROOTDIR=${TC_ORG3_P2_DATA}/snapshots
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:${TC_ORG3_P2_OPPORT}
      # - CORE_OPERATIONS_TLS_CERT_FILE=${TC_ORG3_P2_TLSMSP}/signcerts/cert.pem
      # - CORE_OPERATIONS_TLS_KEY_FILE=${TC_ORG3_P2_TLSMSP}/keystore/key.pem
      # - CORE_OPERATIONS_TLS_CLIENTAUTHREQUIRED=true
      # - CORE_OPERATIONS_TLS_CLIENTROOTCAS_FILES:
      #   - ${TC_ORG3_P2_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_COMMON1_C1_PORT}.pem
      - CORE_PEER_ADDRESS=${TC_ORG3_P2_FQDN}:${TC_ORG3_P2_PORT}
      - CORE_PEER_CHAINCODEADDRESS=${TC_ORG3_P2_FQDN}:${TC_ORG3_P2_CHPORT}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${TC_ORG3_P2_CHPORT}
      - CORE_PEER_ID=${TC_ORG3_P2_CA_NAME}
      - CORE_PEER_FILESYSTEMPATH=${TC_ORG3_P2_DATA}
      - CORE_PEER_GOSSIP_BOOTSTRAP=127.0.0.1:${TC_ORG3_P2_PORT}
      - CORE_PEER_GOSSIP_ENDPOINT=${TC_ORG3_P2_FQDN}:${TC_ORG3_P2_PORT}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${TC_ORG3_P2_FQDN}:${TC_ORG3_P2_PORT}
      - CORE_PEER_GOSSIP_ORGLEADER=true
      # - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_GOSSIP_STATE_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${TC_ORG3_P2_PORT}
      - CORE_PEER_LOCALMSPID=${TC_ORG3_STACK}MSP
      - CORE_PEER_NETWORKID=${TC_SWARM_NETNAME}
      - CORE_PEER_MSPCONFIGPATH=${TC_ORG3_P2_MSP}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=${TC_ORG3_P2_TLSMSP}/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=${TC_ORG3_P2_TLSMSP}/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=${TC_ORG3_P2_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_COMMON1_C1_PORT}.pem
      # - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES:
      #     - ${TC_ORG3_P2_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_COMMON1_C1_PORT}.pem
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${TC_NETWORK_NAME}
      - FABRIC_LOGGING_SPEC=${TC_ORG3_P2_LOGLEVEL}
    hostname: ${TC_ORG3_P2_FQDN}
    image: hyperledger/fabric-peer:${TC_DEPS_FABRIC}
    labels:
      service: ${TC_ORG3_P2_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_ORG3_P2_NAME}
          - ${TC_ORG3_P2_FQDN}
    ports:
      - ${TC_ORG3_P2_PORT}:${TC_ORG3_P2_PORT}
      - ${TC_ORG3_P2_CHPORT}:${TC_ORG3_P2_CHPORT}
      - ${TC_ORG3_P2_OPPORT}:${TC_ORG3_P2_OPPORT}
    volumes:
      - ${TC_ORG3_P2_DATA}:${TC_ORG3_P2_DATA} 
      - /var/run/:/host/var/run/
    working_dir: ${TC_ORG3_P2_DATA}
  ${TC_ORG3_P3_NAME}:
    depends_on:
      - ${TC_ORG3_D3_FQDN}
    deploy:
      placement:
        constraints: [ node.hostname == ${TC_ORG3_P3_WORKER} ]
      replicas: 0
      restart_policy:
        condition: any 
        delay: ${TC_SWARM_DELAY}s
        max_attempts: 5
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=${TC_ORG3_D3_FQDN}:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${TC_ORG3_D3_USER}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${TC_ORG3_D3_USERPW}
      - CORE_LEDGER_SNAPSHOTS_ROOTDIR=${TC_ORG3_P3_DATA}/snapshots
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:${TC_ORG3_P3_OPPORT}
      # - CORE_OPERATIONS_TLS_CERT_FILE=${TC_ORG3_P3_TLSMSP}/signcerts/cert.pem
      # - CORE_OPERATIONS_TLS_KEY_FILE=${TC_ORG3_P3_TLSMSP}/keystore/key.pem
      # - CORE_OPERATIONS_TLS_CLIENTAUTHREQUIRED=true
      # - CORE_OPERATIONS_TLS_CLIENTROOTCAS_FILES:
      #   - ${TC_ORG3_P3_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_COMMON1_C1_PORT}.pem
      - CORE_PEER_ADDRESS=${TC_ORG3_P3_FQDN}:${TC_ORG3_P3_PORT}
      - CORE_PEER_CHAINCODEADDRESS=${TC_ORG3_P3_FQDN}:${TC_ORG3_P3_CHPORT}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${TC_ORG3_P3_CHPORT}
      - CORE_PEER_ID=${TC_ORG3_P3_CA_NAME}
      - CORE_PEER_FILESYSTEMPATH=${TC_ORG3_P3_DATA}
      - CORE_PEER_GOSSIP_BOOTSTRAP=127.0.0.1:${TC_ORG3_P3_PORT}
      - CORE_PEER_GOSSIP_ENDPOINT=${TC_ORG3_P3_FQDN}:${TC_ORG3_P3_PORT}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${TC_ORG3_P3_FQDN}:${TC_ORG3_P3_PORT}
      - CORE_PEER_GOSSIP_ORGLEADER=true
      # - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_GOSSIP_STATE_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${TC_ORG3_P3_PORT}
      - CORE_PEER_LOCALMSPID=${TC_ORG3_STACK}MSP
      - CORE_PEER_NETWORKID=${TC_SWARM_NETNAME}
      - CORE_PEER_MSPCONFIGPATH=${TC_ORG3_P3_MSP}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=${TC_ORG3_P3_TLSMSP}/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=${TC_ORG3_P3_TLSMSP}/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=${TC_ORG3_P3_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_COMMON1_C1_PORT}.pem
      # - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES:
      #     - ${TC_ORG3_P3_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_COMMON1_C1_PORT}.pem
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${TC_NETWORK_NAME}
      - FABRIC_LOGGING_SPEC=${TC_ORG3_P3_LOGLEVEL}
    hostname: ${TC_ORG3_P3_FQDN}
    image: hyperledger/fabric-peer:${TC_DEPS_FABRIC}
    labels:
      service: ${TC_ORG3_P3_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_ORG3_P3_NAME}
          - ${TC_ORG3_P3_FQDN}
    ports:
      - ${TC_ORG3_P3_PORT}:${TC_ORG3_P3_PORT}
      - ${TC_ORG3_P3_CHPORT}:${TC_ORG3_P3_CHPORT}
      - ${TC_ORG3_P3_OPPORT}:${TC_ORG3_P3_OPPORT}
    volumes:
      - ${TC_ORG3_P3_DATA}:${TC_ORG3_P3_DATA} 
      - /var/run/:/host/var/run/
    working_dir: ${TC_ORG3_P3_DATA}

  ${TC_ORG3_CLI1_NAME}:
    command: /bin/bash
    # depends_on:
    #   - ${TC_ORG1_D1_FQDN}
    deploy:
      placement:
        constraints: [ node.hostname == ${TC_ORG3_CLI1_WORKER} ]
      replicas: 1
      restart_policy:
        condition: any 
        delay: ${TC_SWARM_DELAY}s
        max_attempts: 5
    environment:
      - CORE_PEER_ADDRESS=CORE_PEER_ADDRESS=${TC_ORG3_CLI1_PEER_FQDN}:${TC_ORG3_CLI1_PORT}
      - CORE_PEER_ID=${TC_ORG3_CLI1_PEER_NAME}
      - CORE_PEER_LOCALMSPID=${TC_ORG3_STACK}MSP
      - CORE_PEER_MSPCONFIGPATH=${TC_ORG3_CLI1_MSP}
      - CORE_PEER_NETWORKID=${TC_SWARM_NETNAME}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=${TC_ORG3_CLI1_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_COMMON1_C1_PORT}.pem
      # - CORE_PEER_TLS_CERT_FILE=${TC_ORG3_CLI1_TLSMSP}/signcerts/cert.pem
      # - CORE_PEER_TLS_KEY_FILE=${TC_ORG3_CLI1_TLSMSP}/keystore/key.pem
      # - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES:
      #     - ${TC_ORG3_CLI1_TLSMSP}/tlscacerts/tls-0-0-0-0-${TC_COMMON1_C1_PORT}.pem
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=${TC_ORG3_CLI1_LOGLEVEL}
      # - GOPATH=/opt/gopath
      # - GOPATH=${TC_ORG3_CLI1_ASSETS_CHAINCODE}
      - TC_PATH_RC=$TC_PATH_RC
    hostname: ${TC_ORG3_CLI1_FQDN}
    image: hyperledger/fabric-tools:${TC_DEPS_FABRIC}
    labels:
      service: ${TC_ORG3_CLI1_FQDN}
    networks:
      ${TC_SWARM_NETNAME}:
        aliases:
          - ${TC_ORG3_CLI1_NAME}
          - ${TC_ORG3_CLI1_FQDN}
    # ports:
    #   - ${TC_ORG3_CLI1_PORT}:${TC_ORG3_CLI1_PORT}
    #   - ${TC_ORG3_CLI1_CHPORT}:${TC_ORG3_CLI1_CHPORT}
    #   - ${TC_ORG3_CLI1_OPPORT}:${TC_ORG3_CLI1_OPPORT}
    stdin_open: true
    tty: true
    volumes:
      - ${TC_ORG3_DATA}:${TC_ORG3_DATA}
      - ${TC_PATH_SCRIPTS}:${TC_PATH_SCRIPTS}
    working_dir: ${TC_PATH_BASE}
