version: '3.7'

networks:
  ${TC_NETWORK_NAME}:
    name: ${TC_NETWORK_NAME}
    external: true

# volumes:
#   prometheus_data: {}
#   grafana_storage: {}

services:
  ${TC_COMMON1_S1_NAME}:
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    image: dockersamples/visualizer
    networks:
      ${TC_NETWORK_NAME}:
        aliases:
          - ${TC_COMMON1_S1_NAME}
    ports:
      - ${TC_COMMON1_S1_PORT}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ${TC_COMMON1_S2_NAME}:
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    image: gliderlabs/logspout:latest
    networks:
      ${TC_NETWORK_NAME}:
        aliases:
          - ${TC_COMMON1_S2_NAME}
    ports:
      - ${TC_COMMON1_S2_PORT}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ${TC_COMMON1_S3_NAME}:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == ${TC_COMMON1_S3_WORKER} ]
    image: prom/prometheus:latest
    networks:
      ${TC_NETWORK_NAME}:
        aliases:
          - ${TC_COMMON1_S3_NAME}
    ports:
      - ${TC_COMMON1_S3_PORT}:9090
    user: "${TC_COMMON1_UID}:${TC_COMMON1_UID}"
    volumes:
      - ${TC_COMMON1_S3_DATA}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${TC_COMMON1_S3_DATA}:/prometheus:rw
  ${TC_COMMON1_S4_NAME}:
    cap_add:
      - ALL
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == ${TC_COMMON1_S4_WORKER} ]
      restart_policy:
        condition: any 
        delay: ${TC_SWARM_DELAY}s
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      ${TC_NETWORK_NAME}:
        aliases:
          - ${TC_COMMON1_S4_NAME}
    # privileged: true
    ports:
      - ${TC_COMMON1_S4_PORT}:8080
    volumes:
      # - /cgroup:/cgroup:ro
      - /sys/fs/cgroup:/cgroup:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
  ${TC_COMMON1_S5_NAME}:
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == ${TC_COMMON1_S5_WORKER} ]
      restart_policy:
        condition: any 
        delay: ${TC_SWARM_DELAY}s
    image: prom/node-exporter:v1.3.1
    networks:
      ${TC_NETWORK_NAME}:
        aliases:
          - ${TC_COMMON1_S5_NAME}
    ports:
      - ${TC_COMMON1_S5_PORT}:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
  ${TC_COMMON1_S6_NAME}:
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == ${TC_COMMON1_S6_WORKER} ]
    image: grafana/grafana:latest
    user: "${TC_COMMON1_UID}:${TC_COMMON1_GID}"
    networks:
      ${TC_NETWORK_NAME}:
        aliases:
          - ${TC_COMMON1_S6_NAME}
    depends_on:
      - ${TC_COMMON1_S3_NAME}
    ports:
      - ${TC_COMMON1_S6_PORT}:3000
    volumes:
      - ${TC_COMMON1_S6_DATA}:/var/lib/grafana:rw
      - ${TC_COMMON1_S6_DATA}/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ${TC_COMMON1_S6_DATA}/config.monitoring
