port: ${TC_COMMON1_C1_PORT}
debug: ${TC_COMMON1_C1_DEBUG}

tls:
  enabled: true

registry:
  maxenrollments: -1
  identities:
     - name: ${TC_COMMON1_C1_ADMIN}
       pass: ${TC_COMMON1_C1_ADMINPW}
       type: client
      #  affiliation: ${TC_COMMON1_STACK}
       attrs:
          hf.Registrar.Roles: "*"
          hf.Registrar.DelegateRoles: "*"
          hf.Revoker: true
          hf.IntermediateCA: true
          hf.GenCRL: true
          hf.Registrar.Attributes: "*"
          hf.AffiliationMgr: true

signing:
    default:
      expiry: ${TC_COMMON1_C1_EXP}
    profiles:
      ca:
         expiry: ${TC_COMMON1_C1_EXP}
      tls:
         expiry: ${TC_COMMON1_C1_EXP}

csr:
  # cn: ${TC_COMMON1_C1_NAME}-${TC_COMMON1_STACK}
  # names:
  #   - C: "${TC_COMMON1_C}"
  #     ST: "${TC_COMMON1_ST}"
  #     L: "${TC_COMMON1_L}"
  #     O: "${TC_COMMON1_O}"
  #     OU: "${TC_COMMON1_OU}"
  cn: ${TC_COMMON1_STACK}-${TC_COMMON1_C1_NAME}
  names:
    - C:
      ST:
      L:
      O: "${TC_NETWORK_NAME}"
      OU: "${TC_COMMON1_STACK}"
  hosts:
    - ${TC_COMMON1_C1_FQDN}
    - localhost
    - 0.0.0.0
  ca:
    expiry: ${TC_COMMON1_C1_EXP}
