url: https://0.0.0.0:${TC_ORG3_C1_PORT}
# mspdir: msp
debug: false

tls:
  enabled: true

csr:
  cn: ${TC_ORG3_ADMIN}
  names:
    - C:
      ST:
      L:
      OU:
      O: "${TC_ORG3_STACK}"

id:
  name:
  type:
  # affiliation: ${TC_COMMON1_STACK}
  maxenrollments: 0
  attributes:
